webtalk_init -webtalk_dir /home/tad1/Projects/PG_SEM6/ISP/2019.1/lab7/lab7.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-03-29 17:41:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "olftruobf4s6su1h2rvq616cum" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292.134 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.867 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1711728861000" -context "sdk\\\\bsp/1711728861000"
webtalk_add_data -client sdk -key hwid -value "1711715348000" -context "sdk\\\\bsp/1711728861000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1711728861000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1711728861000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1711728861000"
webtalk_add_data -client sdk -key uid -value "1711728862000" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key hwid -value "1711715348000" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key bspid -value "1711728861000" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key projSize -value "134.4375" -context "sdk\\\\application/1711728862000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1711730502102"
webtalk_transmit -clientid 2348478083 -regid "" -xml /home/tad1/Projects/PG_SEM6/ISP/2019.1/lab7/lab7.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/tad1/Projects/PG_SEM6/ISP/2019.1/lab7/lab7.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/tad1/Projects/PG_SEM6/ISP/2019.1/lab7/lab7.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
